export const CREATE_HOUR = "CREATE_HOUR";
export const RETRIEVE_HOURS = "RETRIEVE_HOURS";
export const UPDATE_HOUR = "UPDATE_HOUR";
export const DELETE_HOUR = "DELETE_HOUR";

export const CREATE_DOCTOR = "CREATE_DOCTOR";
export const RETRIEVE_DOCTORS = "RETRIEVE_DOCTORS";
export const UPDATE_DOCTOR = "UPDATE_DOCTOR";
export const DELETE_DOCTOR = "DELETE_DOCTOR";

export const CREATE_REQUEST = "CREATE_REQUEST";
export const RETRIEVE_REQUESTS = "RETRIEVE_REQUESTS";
export const UPDATE_REQUEST = "UPDATE_REQUEST";
export const DELETE_REQUEST = "DELETE_REQUEST";
